"""Atomic Bash presentation slides for Merit Advisory training."""

SLIDES = [{'section': 1,
  'title': 'Function Foundations',
  'topics': [{'id': '04-01-01',
              'title': 'Why functions',
              'points': ['Functions name a reusable piece of shell logic.',
                         'They reduce repeated code in longer scripts.',
                         'They create small units that are easier to test.'],
              'examples': [{'label': 'Repeated action',
                            'code': 'say_hi() { echo "hi $1"; }\nsay_hi Ada'},
                           {'label': 'Named step', 'code': 'build() { make all; }\nbuild'}]},
             {'id': '04-01-02',
              'title': 'Name parentheses braces form',
              'points': ['The name() { } form is common Bash function syntax.',
                         'A space is required before the opening brace body.',
                         'Commands inside the braces run when the function is called.'],
              'examples': [{'label': 'Define', 'code': 'hello() { echo hello; }'},
                           {'label': 'Define and call', 'code': 'hello() { echo hello; }\nhello'}]},
             {'id': '04-01-03',
              'title': 'Function keyword form',
              'points': ['Bash also accepts the function keyword.',
                         'It is less portable but common in Bash-only scripts.',
                         'Pick one style and use it consistently.'],
              'examples': [{'label': 'Keyword', 'code': 'function hello { echo hello; }'},
                           {'label': 'Keyword call',
                            'code': 'function build { echo build; }\nbuild'}]},
             {'id': '04-01-04',
              'title': 'Calling functions',
              'points': ['Call a function by writing its name like a command.',
                         'Arguments follow the name separated by spaces.',
                         'The function must be defined before the call runs.'],
              'examples': [{'label': 'Simple call', 'code': 'greet() { echo hi; }\ngreet'},
                           {'label': 'Call with arg',
                            'code': 'greet() { echo "hi $1"; }\ngreet Sam'}]},
             {'id': '04-01-05',
              'title': 'Declare before use',
              'points': ['Bash executes scripts from top to bottom.',
                         'A function definition must be seen before it is called.',
                         'Place helper definitions near the top of scripts.'],
              'examples': [{'label': 'Before main', 'code': 'helper() { echo help; }\nhelper'},
                           {'label': 'Main last',
                            'code': 'main() { helper; }\nhelper() { echo h; }'}]},
             {'id': '04-01-06',
              'title': 'Function call status',
              'points': ['A function returns the status of its last command by default.',
                         'That status can drive if, &&, and ||.',
                         'Use return when the last command is not the intended status.'],
              'examples': [{'label': 'Status from grep',
                            'code': 'has_root() { grep -q root /etc/passwd; }\n'
                                    'has_root && echo yes'},
                           {'label': 'Status from test',
                            'code': 'exists() { [[ -e $1 ]]; }\nexists file || echo missing'}]},
             {'id': '04-01-07',
              'title': 'Compose small functions',
              'points': ['Small functions are easier to name and reuse.',
                         'One function should do one clear job.',
                         'Compose larger workflows from smaller helpers.'],
              'examples': [{'label': 'Two helpers',
                            'code': 'clean() { rm -rf out; }\nbuild() { mkdir out; }'},
                           {'label': 'Workflow',
                            'code': 'run_all() { clean && build; }\nrun_all'}]}]},
 {'section': 2,
  'title': 'Function Parameters',
  'topics': [{'id': '04-02-01',
              'title': 'First argument inside a function',
              'points': ['$1 inside a function is the function first argument.',
                         'It is separate from the script first argument.',
                         'Quote it when using it as data.'],
              'examples': [{'label': 'Print first', 'code': 'show() { echo "$1"; }\nshow alpha'},
                           {'label': 'Use path',
                            'code': 'size() { wc -c < "$1"; }\nsize file.txt'}]},
             {'id': '04-02-02',
              'title': 'All arguments with dollar at',
              'points': ['"$@" expands to all function arguments safely.',
                         'Each original argument stays a separate word.',
                         'Use it when forwarding arguments to another command.'],
              'examples': [{'label': 'Forward', 'code': 'run() { command "$@"; }\nrun echo hi'},
                           {'label': 'List args',
                            'code': 'show() { printf \'%s\\n\' "$@"; }\nshow a "b c"'}]},
             {'id': '04-02-03',
              'title': 'Argument count',
              'points': ['$# is the number of arguments passed to the function.',
                         'Use it for arity checks.',
                         'Check counts before reading required parameters.'],
              'examples': [{'label': 'Require one',
                            'code': 'need_one() { [[ $# -eq 1 ]] || return 2; }'},
                           {'label': 'Print count',
                            'code': 'count_args() { echo "$#"; }\ncount_args a b'}]},
             {'id': '04-02-04',
              'title': 'Default arguments',
              'points': ['Parameter expansion can provide defaults.',
                         'Defaults make optional parameters explicit.',
                         'Use local variables to name defaulted values.'],
              'examples': [{'label': 'Default env',
                            'code': 'deploy() { local env=${1:-dev}; echo "$env"; }'},
                           {'label': 'Default file',
                            'code': 'read_cfg() { local cfg=${1:-config.env}; echo "$cfg"; }'}]},
             {'id': '04-02-05',
              'title': 'Shift inside functions',
              'points': ['shift removes the first function argument.',
                         'It is useful after parsing an option or command.',
                         'It does not shift the script arguments outside the function.'],
              'examples': [{'label': 'Drop command',
                            'code': 'run_cmd() { local cmd=$1; shift; "$cmd" "$@"; }'},
                           {'label': 'Parse first',
                            'code': 'show_rest() { local first=$1; shift; printf \'%s\\n\' "$@"; '
                                    '}'}]},
             {'id': '04-02-06',
              'title': 'Validate function arguments',
              'points': ['Functions should check the inputs they require.',
                         'Return a nonzero status when validation fails.',
                         'Keep validation close to the top of the function.'],
              'examples': [{'label': 'Require file',
                            'code': 'read_file() { [[ -r $1 ]] || return 2; wc -l < "$1"; }'},
                           {'label': 'Require int',
                            'code': 'twice() { [[ $1 =~ ^[0-9]+$ ]] || return 2; echo $(($1*2)); '
                                    '}'}]},
             {'id': '04-02-07',
              'title': 'Usage function',
              'points': ['A usage function prints the valid command form.',
                         'Keep it short enough to read after an error.',
                         'Call it from argument validation branches.'],
              'examples': [{'label': 'Usage text', 'code': 'usage() { echo "usage: app FILE"; }'},
                           {'label': 'Use usage',
                            'code': '[[ $# -eq 1 ]] || { usage; exit 2; }'}]}]},
 {'section': 3,
  'title': 'Scope And Local State',
  'topics': [{'id': '04-03-01',
              'title': 'Local variables',
              'points': ['local creates a variable scoped to the current function.',
                         'It prevents accidental changes to global variables.',
                         'Use local for temporary function state.'],
              'examples': [{'label': 'Local name',
                            'code': 'greet() { local name=$1; echo "hi $name"; }'},
                           {'label': 'Local count',
                            'code': 'count() { local n=0; ((n++)); echo $n; }'}]},
             {'id': '04-03-02',
              'title': 'Missing local pitfall',
              'points': ['Assignments without local can change global variables.',
                         'This can create surprising behavior between functions.',
                         'Declare scratch variables local by default.'],
              'examples': [{'label': 'Global leak', 'code': 'tmp=old\nset_tmp() { tmp=new; }'},
                           {'label': 'Fixed',
                            'code': 'set_tmp() { local tmp=new; echo "$tmp"; }'}]},
             {'id': '04-03-03',
              'title': 'Readonly function variables',
              'points': ['readonly prevents reassignment after a value is set.',
                         'Inside functions, combine local and readonly for constants.',
                         'Use it for values that must not change within a helper.'],
              'examples': [{'label': 'Local readonly',
                            'code': 'show() { local -r path=$1; echo "$path"; }'},
                           {'label': 'Readonly global', 'code': 'readonly APP_NAME=demo'}]},
             {'id': '04-03-04',
              'title': 'Global variables are shared state',
              'points': ['Global variables are visible inside functions.',
                         'They couple helpers to outer script state.',
                         'Prefer parameters and outputs for most data flow.'],
              'examples': [{'label': 'Read global',
                            'code': 'prefix=app\nname() { echo "$prefix-$1"; }'},
                           {'label': 'Avoid write',
                            'code': 'set_env() { local env=$1; echo "$env"; }'}]},
             {'id': '04-03-05',
              'title': 'Local arrays',
              'points': ['Arrays can be local to a function.',
                         'Use local -a for indexed arrays.',
                         'Quote array expansions when passing values along.'],
              'examples': [{'label': 'Local array',
                            'code': 'list() { local -a xs=(a b); printf \'%s\\n\' "${xs[@]}"; }'},
                           {'label': 'Build array',
                            'code': 'make_args() { local -a args=(--name "$1"); printf \'%s\\n\' '
                                    '"${args[@]}"; }'}]},
             {'id': '04-03-06',
              'title': 'Nameref intro',
              'points': ['local -n creates a nameref to another variable.',
                         'It lets a function update a caller variable by name.',
                         'Use it carefully because it increases coupling.'],
              'examples': [{'label': 'Set by name',
                            'code': 'set_value() { local -n ref=$1; ref=$2; }\n'
                                    'set_value result ok'},
                           {'label': 'Array by name',
                            'code': 'first_item() { local -n arr=$1; echo "${arr[0]}"; }'}]},
             {'id': '04-03-07',
              'title': 'Unset temporary names',
              'points': ['unset removes a variable name from the current scope.',
                         'Local variables disappear automatically when a function returns.',
                         'Use unset when a long function must clear sensitive values early.'],
              'examples': [{'label': 'Unset local',
                            'code': 'demo() { local token=$1; unset token; }'},
                           {'label': 'Unset global', 'code': 'cache=value\nunset cache'}]}]},
 {'section': 4,
  'title': 'Return Values And Output',
  'topics': [{'id': '04-04-01',
              'title': 'Return status',
              'points': ['return sets the function exit status.',
                         'A status of 0 means success.',
                         'Use nonzero statuses for validation or command failures.'],
              'examples': [{'label': 'Return success',
                            'code': 'ok() { return 0; }\nok && echo yes'},
                           {'label': 'Return failure',
                            'code': 'fail() { return 1; }\nfail || echo no'}]},
             {'id': '04-04-02',
              'title': 'Return status range',
              'points': ['Shell return statuses are small integers.',
                         'Do not use return for strings or structured data.',
                         'Use stdout for data a caller should capture.'],
              'examples': [{'label': 'Bad data return', 'code': 'get_name() { echo Ada; }'},
                           {'label': 'Status only', 'code': 'is_file() { [[ -f $1 ]]; }'}]},
             {'id': '04-04-03',
              'title': 'Return versus echo',
              'points': ['return communicates success or failure.',
                         'echo or printf communicates textual output.',
                         'Keep status and data roles separate.'],
              'examples': [{'label': 'Predicate', 'code': 'is_prod() { [[ $1 == prod ]]; }'},
                           {'label': 'Producer',
                            'code': 'make_name() { printf \'app-%s\\n\' "$1"; }'}]},
             {'id': '04-04-04',
              'title': 'Capture command substitution',
              'points': ['Command substitution captures stdout from a function.',
                         'Trailing newlines are removed by the substitution.',
                         'Quote the assignment result when using it later.'],
              'examples': [{'label': 'Capture', 'code': 'now() { date +%s; }\nts=$(now)'},
                           {'label': 'Capture name',
                            'code': 'slug() { echo "app-$1"; }\nname=$(slug api)'}]},
             {'id': '04-04-05',
              'title': 'Stdout versus stderr',
              'points': ['Stdout is for data a caller may capture.',
                         'Stderr is for diagnostics and errors.',
                         'Send messages to stderr when stdout must stay parseable.'],
              'examples': [{'label': 'Error output', 'code': 'warn() { echo "warn: $*" >&2; }'},
                           {'label': 'Data output', 'code': 'value() { printf \'%s\\n\' "$1"; }'}]},
             {'id': '04-04-06',
              'title': 'Quiet predicate functions',
              'points': ['Predicate functions often print nothing.',
                         'Their status is the answer.',
                         'This makes them easy to use in if statements.'],
              'examples': [{'label': 'Has command',
                            'code': 'has_cmd() { command -v "$1" >/dev/null 2>&1; }'},
                           {'label': 'Readable', 'code': 'can_read() { [[ -r $1 ]]; }'}]},
             {'id': '04-04-07',
              'title': 'Multiple values with echo',
              'points': ['A function can print multiple lines as output.',
                         'The caller must parse that output deliberately.',
                         'For complex data, prefer clear formats or separate helpers.'],
              'examples': [{'label': 'Two lines', 'code': "pair() { printf '%s\\n' name Ada; }"},
                           {'label': 'Parse simple',
                            'code': 'vals=$(pair)\nprintf \'%s\\n\' "$vals"'}]}]},
 {'section': 5,
  'title': 'Main Pattern And Libraries',
  'topics': [{'id': '04-05-01',
              'title': 'Main function pattern',
              'points': ['A main function names the script entry point.',
                         'It keeps top-level code short.',
                         'It makes script flow easier to scan.'],
              'examples': [{'label': 'Main', 'code': 'main() { echo run; }\nmain "$@"'},
                           {'label': 'Main status', 'code': 'main() { return 0; }\nmain "$@"'}]},
             {'id': '04-05-02',
              'title': 'Pass arguments to main',
              'points': ['Use "$@" when calling main from top level.',
                         'This preserves the original script arguments.',
                         'Main can then validate and dispatch them.'],
              'examples': [{'label': 'Forward all',
                            'code': 'main() { printf \'%s\\n\' "$@"; }\nmain "$@"'},
                           {'label': 'Use first', 'code': 'main() { echo "cmd=$1"; }\nmain "$@"'}]},
             {'id': '04-05-03',
              'title': 'Sourcing a library',
              'points': ['source reads another shell file into the current shell.',
                         'Functions defined there become available to the script.',
                         'Use relative paths carefully when sourcing libraries.'],
              'examples': [{'label': 'Source lib', 'code': 'source ./lib.sh\nhelper'},
                           {'label': 'Dot form', 'code': '. ./lib.sh\nhelper'}]},
             {'id': '04-05-04',
              'title': 'Guard against re source',
              'points': ['A guard variable can prevent loading a library twice.',
                         'Set the guard after the first successful load.',
                         'This protects repeated readonly declarations.'],
              'examples': [{'label': 'Library guard',
                            'code': '[[ ${LIB_LOADED:-} ]] && return 0\nLIB_LOADED=1'},
                           {'label': 'Readonly guard',
                            'code': '[[ ${UTILS_LOADED:-} ]] && return 0\n'
                                    'readonly UTILS_LOADED=1'}]},
             {'id': '04-05-05',
              'title': 'Function library layout',
              'points': ['Group related helper functions in a small library file.',
                         'Keep script entry logic out of reusable libraries.',
                         'Use clear prefixes when many libraries are sourced.'],
              'examples': [{'label': 'Utils file', 'code': 'log_info() { echo "info: $*"; }'},
                           {'label': 'Script use', 'code': 'source ./utils.sh\nlog_info start'}]},
             {'id': '04-05-06',
              'title': 'Helpers before main',
              'points': ['Place helper definitions before main calls them.',
                         'This matches Bash top to bottom execution.',
                         'The main call should usually be near the end.'],
              'examples': [{'label': 'Order', 'code': 'helper() { echo h; }\nmain() { helper; }'},
                           {'label': 'Call last', 'code': 'main() { echo run; }\nmain "$@"'}]},
             {'id': '04-05-07',
              'title': 'Run only when executed',
              'points': ['BASH_SOURCE can distinguish source from execute.',
                         'This allows a file to be both script and library.',
                         'Call main only when the file is executed directly.'],
              'examples': [{'label': 'Entry guard',
                            'code': 'if [[ ${BASH_SOURCE[0]} == $0 ]]; then main "$@"; fi'},
                           {'label': 'Source safe',
                            'code': 'main() { echo run; }\n'
                                    '[[ ${BASH_SOURCE[0]} == $0 ]] && main "$@"'}]}]},
 {'section': 6,
  'title': 'Error Logging And Assertions',
  'topics': [{'id': '04-06-01',
              'title': 'Die helper',
              'points': ['A die helper prints an error and exits.',
                         'It centralizes fatal error formatting.',
                         'Use it only where exiting the script is intended.'],
              'examples': [{'label': 'Die', 'code': 'die() { echo "error: $*" >&2; exit 1; }'},
                           {'label': 'Use die', 'code': '[[ -r $cfg ]] || die "missing config"'}]},
             {'id': '04-06-02',
              'title': 'Error helper',
              'points': ['An error helper prints to stderr without exiting.',
                         'It lets callers decide whether to return or continue.',
                         'This is useful inside reusable functions.'],
              'examples': [{'label': 'Error', 'code': 'error() { echo "error: $*" >&2; }'},
                           {'label': 'Return after error',
                            'code': 'need_file() { [[ -f $1 ]] || { error missing; return 2; }; '
                                    '}'}]},
             {'id': '04-06-03',
              'title': 'Info logging helper',
              'points': ['An info helper marks normal progress messages.',
                         'Send logs to stderr when stdout is data.',
                         'Keep the format consistent across scripts.'],
              'examples': [{'label': 'Info', 'code': 'info() { echo "info: $*" >&2; }'},
                           {'label': 'Use info', 'code': 'info "starting build"'}]},
             {'id': '04-06-04',
              'title': 'Warn logging helper',
              'points': ['A warn helper marks nonfatal problems.',
                         'It should not exit on its own.',
                         'Use it when the script can continue safely.'],
              'examples': [{'label': 'Warn', 'code': 'warn() { echo "warn: $*" >&2; }'},
                           {'label': 'Use warn',
                            'code': '[[ -f optional.env ]] || warn "no optional env"'}]},
             {'id': '04-06-05',
              'title': 'Assert command helper',
              'points': ['An assert helper checks an invariant during a script.',
                         'Failed assertions should return or exit clearly.',
                         'Use assertions for programmer expectations, not user input.'],
              'examples': [{'label': 'Assert',
                            'code': 'assert() { "$@" || die "assert failed: $*"; }'},
                           {'label': 'Assert use', 'code': 'assert test -d src'}]},
             {'id': '04-06-06',
              'title': 'Assert file helper',
              'points': ['A file assertion names a common required condition.',
                         'It keeps call sites short and readable.',
                         'Return nonzero rather than exiting inside reusable libraries.'],
              'examples': [{'label': 'Require file',
                            'code': 'require_file() { [[ -f $1 ]] || return 2; }'},
                           {'label': 'Use require',
                            'code': 'require_file config.env || die "need config"'}]},
             {'id': '04-06-07',
              'title': 'Command wrapper',
              'points': ['A wrapper function adds policy around another command.',
                         'It can add logging, defaults, or validation.',
                         'Forward arguments with "$@" to preserve words.'],
              'examples': [{'label': 'Git wrapper',
                            'code': 'git_checked() { git "$@" || die "git failed"; }'},
                           {'label': 'Curl wrapper', 'code': 'fetch() { curl -fsS "$@"; }'}]}]},
 {'section': 7,
  'title': 'Advanced Function Mechanics',
  'topics': [{'id': '04-07-01',
              'title': 'Functions and exit',
              'points': ['exit inside a function exits the shell or script.',
                         'return exits only the function.',
                         'Library functions should usually return instead of exit.'],
              'examples': [{'label': 'Return', 'code': 'check() { [[ -e $1 ]] || return 2; }'},
                           {'label': 'Exit fatal', 'code': 'fatal() { echo bad >&2; exit 1; }'}]},
             {'id': '04-07-02',
              'title': 'Set e inside functions',
              'points': ['set -e can interact with function calls in surprising ways.',
                         'Commands tested by if or || are treated specially.',
                         'Use explicit status handling for important failures.'],
              'examples': [{'label': 'Explicit return',
                            'code': 'copy() { cp "$1" "$2" || return; }'},
                           {'label': 'If tested', 'code': 'if risky_fn; then echo ok; fi'}]},
             {'id': '04-07-03',
              'title': 'Err trap caution',
              'points': ['ERR traps can run when commands fail under set -e.',
                         'Functions make trap flow harder to reason about.',
                         'Keep trap based error handling small and tested.'],
              'examples': [{'label': 'Err trap', 'code': "trap 'echo failed >&2' ERR\nset -E"},
                           {'label': 'Function failure', 'code': 'work() { false; }\nwork'}]},
             {'id': '04-07-04',
              'title': 'Recursion caution',
              'points': ['Bash functions can call themselves recursively.',
                         'Deep recursion is usually a poor fit for shell scripts.',
                         'Prefer loops for repeated shell work.'],
              'examples': [{'label': 'Recursive shape',
                            'code': 'countdown() { (( $1 == 0 )) || countdown $(($1-1)); }'},
                           {'label': 'Loop alternative',
                            'code': 'for ((n=3; n>=0; n--)); do echo $n; done'}]},
             {'id': '04-07-05',
              'title': 'Overriding commands',
              'points': ['A function can have the same name as a command.',
                         'This changes what unqualified calls run.',
                         'Use command to bypass a function wrapper.'],
              'examples': [{'label': 'Wrapper', 'code': 'ls() { command ls --color=auto "$@"; }'},
                           {'label': 'Bypass', 'code': 'command ls'}]},
             {'id': '04-07-06',
              'title': 'Builtin command bypass',
              'points': ['The command builtin skips shell function lookup.',
                         'It is useful inside wrappers that call the original command.',
                         'It can also check external command availability.'],
              'examples': [{'label': 'Call original',
                            'code': 'grep() { command grep --color=auto "$@"; }'},
                           {'label': 'Find command', 'code': 'command -v bash >/dev/null'}]},
             {'id': '04-07-07',
              'title': 'Unset function',
              'points': ['unset -f removes a function definition.',
                         'It is useful in interactive shells and tests.',
                         'Avoid removing shared helpers during normal script flow.'],
              'examples': [{'label': 'Remove function',
                            'code': 'tmp_fn() { echo tmp; }\nunset -f tmp_fn'},
                           {'label': 'Replace wrapper', 'code': 'unset -f ls'}]}]},
 {'section': 8,
  'title': 'Function Introspection',
  'topics': [{'id': '04-08-01',
              'title': 'Declare f',
              'points': ['declare -f prints function definitions.',
                         'It is useful for debugging sourced libraries.',
                         'Use a function name to inspect one definition.'],
              'examples': [{'label': 'Show function',
                            'code': 'hello() { echo hi; }\ndeclare -f hello'},
                           {'label': 'All functions', 'code': 'declare -f'}]},
             {'id': '04-08-02',
              'title': 'Type t function',
              'points': ['type -t reports what kind of name Bash resolves.',
                         'It prints function for function names.',
                         'It is useful before overriding or dispatching names.'],
              'examples': [{'label': 'Check type', 'code': 'hello() { :; }\ntype -t hello'},
                           {'label': 'Command type', 'code': 'type -t cd'}]},
             {'id': '04-08-03',
              'title': 'Command V',
              'points': ['command -V describes how a name will be interpreted.',
                         'It can show functions, builtins, aliases, and files.',
                         'Use it when debugging resolution problems.'],
              'examples': [{'label': 'Describe', 'code': 'hello() { :; }\ncommand -V hello'},
                           {'label': 'Describe ls', 'code': 'command -V ls'}]},
             {'id': '04-08-04',
              'title': 'Declare F',
              'points': ['declare -F lists function names without bodies.',
                         'It is shorter than declare -f for inventories.',
                         'Use it to confirm a library loaded expected helpers.'],
              'examples': [{'label': 'List names', 'code': 'declare -F'},
                           {'label': 'Has name',
                            'code': 'declare -F helper >/dev/null && echo loaded'}]},
             {'id': '04-08-05',
              'title': 'Exported functions caution',
              'points': ['export -f can pass functions to child Bash processes.',
                         'It is Bash specific and should be used sparingly.',
                         'Prefer script files for reusable child process behavior.'],
              'examples': [{'label': 'Export function',
                            'code': 'helper() { echo h; }\nexport -f helper'},
                           {'label': 'Child bash', 'code': 'bash -c helper'}]},
             {'id': '04-08-06',
              'title': 'Readonly functions',
              'points': ['readonly -f prevents a function from being redefined or unset.',
                         'It can protect critical helpers in controlled scripts.',
                         'Use it sparingly because it makes tests harder.'],
              'examples': [{'label': 'Protect', 'code': 'die() { exit 1; }\nreadonly -f die'},
                           {'label': 'Check readonly', 'code': 'readonly -f'}]},
             {'id': '04-08-07',
              'title': 'Namespace prefixes',
              'points': ['Prefixes reduce function name collisions.',
                         'They are helpful in sourced libraries.',
                         'Use consistent names such as log_info or path_join.'],
              'examples': [{'label': 'Prefixed log', 'code': 'log_info() { echo "info: $*"; }'},
                           {'label': 'Prefixed path', 'code': 'path_join() { echo "$1/$2"; }'}]}]},
 {'section': 9,
  'title': 'Manual Testing And Documentation',
  'topics': [{'id': '04-09-01',
              'title': 'Manual function calls',
              'points': ['Source a file and call functions directly while developing.',
                         'This shortens the edit and test loop.',
                         'Use simple arguments that cover success and failure.'],
              'examples': [{'label': 'Source then call', 'code': 'source ./script.sh\nmy_fn test'},
                           {'label': 'Call failure', 'code': 'my_fn missing || echo failed'}]},
             {'id': '04-09-02',
              'title': 'Interactive source testing',
              'points': ['An interactive shell can load your helpers with source.',
                         'declare -f confirms the definitions are present.',
                         'unset -f can clean up test definitions.'],
              'examples': [{'label': 'Load', 'code': 'source ./lib.sh\ndeclare -F'},
                           {'label': 'Cleanup', 'code': 'unset -f helper'}]},
             {'id': '04-09-03',
              'title': 'Temporary argument tests',
              'points': ['Small test calls can exercise argument handling.',
                         'Include spaces in sample arguments.',
                         'Verify both output and status.'],
              'examples': [{'label': 'Space arg',
                            'code': 'show() { printf \'<%s>\\n\' "$@"; }\nshow "a b"'},
                           {'label': 'Status arg',
                            'code': 'need_one() { [[ $# -eq 1 ]]; }\nneed_one a b || echo bad'}]},
             {'id': '04-09-04',
              'title': 'Capture output tests',
              'points': ['Command substitution can check function output.',
                         'Compare captured output to the expected value.',
                         'Quote variables in test comparisons.'],
              'examples': [{'label': 'Output check',
                            'code': 'got=$(slug api)\n[[ $got == app-api ]]'},
                           {'label': 'Print failure',
                            'code': '[[ $got == ok ]] || echo "got $got"'}]},
             {'id': '04-09-05',
              'title': 'Compare status tests',
              'points': ['Status tests check whether predicates succeed or fail.',
                         'Use if or && and || for manual checks.',
                         'Avoid reading $? when direct conditionals are clearer.'],
              'examples': [{'label': 'Predicate pass',
                            'code': 'is_num() { [[ $1 =~ ^[0-9]+$ ]]; }\nis_num 42 && echo pass'},
                           {'label': 'Predicate fail', 'code': 'is_num x || echo fail'}]},
             {'id': '04-09-06',
              'title': 'ShellCheck SC2155 note',
              'points': ['SC2155 warns about declaring and assigning in one command.',
                         'Separate declaration from assignment when status matters.',
                         'This is especially useful with command substitution.'],
              'examples': [{'label': 'Separated local', 'code': 'local value\nvalue=$(cmd)'},
                           {'label': 'Simple local', 'code': 'local name=$1'}]},
             {'id': '04-09-07',
              'title': 'Documentation comments',
              'points': ['A short comment can describe a function contract.',
                         'Mention inputs, output, and status when helpful.',
                         'Keep comments close to the function definition.'],
              'examples': [{'label': 'Contract',
                            'code': '# Prints a slug for one name.\nslug() { echo "app-$1"; }'},
                           {'label': 'Status comment',
                            'code': '# Returns 0 when the path is readable.\n'
                                    'can_read() { [[ -r $1 ]]; }'}]}]},
 {'section': 10,
  'title': 'Refactoring Into Functions',
  'topics': [{'id': '04-10-01',
              'title': 'Extract repeated code',
              'points': ['Repeated command sequences are good function candidates.',
                         'Name the extracted behavior by its purpose.',
                         'Keep the call site shorter after extraction.'],
              'examples': [{'label': 'Extract', 'code': 'backup() { cp "$1" "$1.bak"; }'},
                           {'label': 'Reuse', 'code': 'backup app.conf\nbackup db.conf'}]},
             {'id': '04-10-02',
              'title': 'Pure functions',
              'points': ['A pure style uses parameters and stdout without hidden state.',
                         'It is easier to test and reuse.',
                         'Shell functions are often not perfectly pure, but the idea helps.'],
              'examples': [{'label': 'Pure slug',
                            'code': 'slug() { printf \'%s\\n\' "${1// /-}"; }'},
                           {'label': 'Capture pure', 'code': 'name=$(slug "api server")'}]},
             {'id': '04-10-03',
              'title': 'Side effect functions',
              'points': ['Side effect functions change files, directories, or process state.',
                         'Name them with verbs so the change is obvious.',
                         'Validate inputs before making changes.'],
              'examples': [{'label': 'Make directory',
                            'code': 'ensure_dir() { [[ -d $1 ]] || mkdir -p "$1"; }'},
                           {'label': 'Remove file',
                            'code': 'remove_file() { [[ -f $1 ]] && rm "$1"; }'}]},
             {'id': '04-10-04',
              'title': 'Limit global dependencies',
              'points': ['Functions that rely on globals are harder to reuse.',
                         'Pass paths and options as arguments instead.',
                         'Keep unavoidable globals readonly when possible.'],
              'examples': [{'label': 'Pass path', 'code': 'load_cfg() { source "$1"; }'},
                           {'label': 'Avoid hidden path',
                            'code': 'run_tool() { local bin=$1; shift; "$bin" "$@"; }'}]},
             {'id': '04-10-05',
              'title': 'Small predicate helpers',
              'points': ['Predicate helpers wrap common tests behind clear names.',
                         'They should return status and usually print nothing.',
                         'This makes if statements read like intent.'],
              'examples': [{'label': 'Predicate',
                            'code': 'is_readable_file() { [[ -f $1 && -r $1 ]]; }'},
                           {'label': 'Use predicate',
                            'code': 'if is_readable_file config; then echo ok; fi'}]},
             {'id': '04-10-06',
              'title': 'Wrap pipelines',
              'points': ['A pipeline can be hidden behind a named function.',
                         'The name documents what the pipeline produces.',
                         'Be clear whether stdout is data or logs.'],
              'examples': [{'label': 'Count errors',
                            'code': 'count_errors() { grep -c ERROR "$1"; }'},
                           {'label': 'Top names',
                            'code': 'top_names() { cut -d, -f1 "$1" | sort; }'}]},
             {'id': '04-10-07',
              'title': 'Teardown helpers',
              'points': ['Cleanup code is a good candidate for a helper.',
                         'A named cleanup function can be used with trap.',
                         'Keep cleanup safe to call more than once.'],
              'examples': [{'label': 'Cleanup', 'code': 'cleanup() { rm -rf "$tmpdir"; }'},
                           {'label': 'Trap cleanup', 'code': 'trap cleanup EXIT'}]}]},
 {'section': 11,
  'title': 'Data Flow Techniques',
  'topics': [{'id': '04-11-01',
              'title': 'Printf v assignment',
              'points': ['printf -v assigns formatted text to a variable by name.',
                         'It avoids command substitution for simple formatting.',
                         'Use it when building strings inside functions.'],
              'examples': [{'label': 'Assign formatted', 'code': 'printf -v name \'app-%s\' "$1"'},
                           {'label': 'Inside function',
                            'code': 'make_name() { printf -v result \'app-%s\' "$1"; }'}]},
             {'id': '04-11-02',
              'title': 'Nameref output',
              'points': ['A nameref can act like an output parameter.',
                         'The caller passes the variable name to update.',
                         'Document this clearly because it is less obvious than stdout.'],
              'examples': [{'label': 'Output variable',
                            'code': 'make_name() { local -n out=$1; out=app; }\nmake_name result'},
                           {'label': 'Status with output',
                            'code': 'find_cfg() { local -n out=$1; out=config.env; }'}]},
             {'id': '04-11-03',
              'title': 'Global output discouraged',
              'points': ['Writing results into globals couples caller and function.',
                         'It can be acceptable in tiny scripts but scales poorly.',
                         'Prefer stdout or nameref outputs for reusable helpers.'],
              'examples': [{'label': 'Global result',
                            'code': 'RESULT=\nset_result() { RESULT=ok; }'},
                           {'label': 'Stdout result', 'code': 'get_result() { echo ok; }'}]},
             {'id': '04-11-04',
              'title': 'Arrays passed by name',
              'points': ['Bash arrays are often passed to functions by variable name.',
                         'local -n lets the function read or update that array.',
                         'Avoid using the same nameref name as the caller array.'],
              'examples': [{'label': 'Read array',
                            'code': 'first() { local -n a=$1; echo "${a[0]}"; }'},
                           {'label': 'Append array',
                            'code': 'add_item() { local -n a=$1; a+=("$2"); }'}]},
             {'id': '04-11-05',
              'title': 'Read loop in function',
              'points': ['A function can own a while read loop.',
                         'Pass the input path as an argument.',
                         'Keep the loop output format stable.'],
              'examples': [{'label': 'Print lines',
                            'code': 'print_file() { while IFS= read -r l; do echo "$l"; done < '
                                    '"$1"; }'},
                           {'label': 'Count lines',
                            'code': 'count_file() { local n=0; while read -r _; do ((n++)); done < '
                                    '"$1"; echo $n; }'}]},
             {'id': '04-11-06',
              'title': 'Mapfile in function',
              'points': ['mapfile can load function input into a local array.',
                         'Use -t to remove trailing newlines.',
                         'This is useful when multiple passes over lines are needed.'],
              'examples': [{'label': 'Local mapfile',
                            'code': 'load_lines() { local -a lines; mapfile -t lines < "$1"; echo '
                                    '"${#lines[@]}"; }'},
                           {'label': 'Print first',
                            'code': 'first_line() { local -a l; mapfile -t l < "$1"; echo '
                                    '"${l[0]}"; }'}]},
             {'id': '04-11-07',
              'title': 'Stable output format',
              'points': ['Function output becomes an interface for callers.',
                         'Changing columns or separators can break scripts.',
                         'Use printf for predictable formatting.'],
              'examples': [{'label': 'Key value',
                            'code': 'emit_pair() { printf \'%s=%s\\n\' "$1" "$2"; }'},
                           {'label': 'One per line',
                            'code': 'emit_list() { printf \'%s\\n\' "$@"; }'}]}]},
 {'section': 12,
  'title': 'Checkpoint Labs',
  'topics': [{'id': '04-12-01',
              'title': 'Build usage lab',
              'points': ['Write a usage function for one script command.',
                         'Call it when arguments are missing or invalid.',
                         'Return status 2 for usage errors.'],
              'examples': [{'label': 'Usage', 'code': 'usage() { echo "usage: app build|test"; }'},
                           {'label': 'Usage error',
                            'code': '[[ $# -gt 0 ]] || { usage; exit 2; }'}]},
             {'id': '04-12-02',
              'title': 'Refactor script lab',
              'points': ['Find two repeated command groups in a script.',
                         'Extract each group into a named function.',
                         'Call the new functions from main.'],
              'examples': [{'label': 'Extract build', 'code': 'build_app() { make build; }'},
                           {'label': 'Main uses', 'code': 'main() { build_app && test_app; }'}]},
             {'id': '04-12-03',
              'title': 'Validator lab',
              'points': ['Create predicate functions for common input checks.',
                         'Keep predicate output quiet.',
                         'Use the predicates in if statements.'],
              'examples': [{'label': 'Integer predicate',
                            'code': 'is_int() { [[ $1 =~ ^-?[0-9]+$ ]]; }'},
                           {'label': 'Path predicate', 'code': 'is_dir() { [[ -d $1 ]]; }'}]},
             {'id': '04-12-04',
              'title': 'Logging library lab',
              'points': ['Create info, warn, and error helpers.',
                         'Send all log messages to stderr.',
                         'Use a consistent prefix for each severity.'],
              'examples': [{'label': 'Info warn',
                            'code': 'info() { echo "info: $*" >&2; }\n'
                                    'warn() { echo "warn: $*" >&2; }'},
                           {'label': 'Error', 'code': 'error() { echo "error: $*" >&2; }'}]},
             {'id': '04-12-05',
              'title': 'Retry function lab',
              'points': ['Wrap retry behavior in a function.',
                         'Accept the command and its arguments with "$@".',
                         'Return failure after the final attempt.'],
              'examples': [{'label': 'Retry shape',
                            'code': 'retry() { for i in 1 2 3; do "$@" && return 0; done; return '
                                    '1; }'},
                           {'label': 'Use retry', 'code': 'retry curl -fsS http://localhost'}]},
             {'id': '04-12-06',
              'title': 'Dispatch function lab',
              'points': ['Use case inside main to choose a function.',
                         'Keep command names separate from implementation details.',
                         'Route unknown commands to usage.'],
              'examples': [{'label': 'Dispatch',
                            'code': 'case $1 in build) build ;; test) test_all ;; *) usage ;; '
                                    'esac'},
                           {'label': 'Function command',
                            'code': 'build() { echo build; }\ntest_all() { echo test; }'}]},
             {'id': '04-12-07',
              'title': 'Function checklist',
              'points': ['Name the function by the job it performs.',
                         'Declare local variables for temporary state.',
                         'Separate status, logs, and data output deliberately.'],
              'examples': [{'label': 'Checklist helper', 'code': 'has_file() { [[ -f $1 ]]; }'},
                           {'label': 'Checklist output',
                            'code': 'make_slug() { printf \'%s\\n\' "${1// /-}"; }'}]}]}]
