"""Atomic Bash presentation slides for Merit Advisory training."""

SLIDES = [{'section': 1,
  'title': 'Exit Status Fundamentals',
  'topics': [{'id': '03-01-01',
              'title': 'Exit status means success or failure',
              'points': ['Every command finishes with a numeric exit status.',
                         'Status 0 means success in Bash conditionals.',
                         'Any nonzero status means failure for control flow.'],
              'examples': [{'label': 'Success status', 'code': 'true\necho $?'},
                           {'label': 'Failure status', 'code': 'false\necho $?'}]},
             {'id': '03-01-02',
              'title': 'true is a successful command',
              'points': ['The true command exists only to return success.',
                         'It is useful when a loop or branch needs a placeholder.',
                         'It documents that success is intentional.'],
              'examples': [{'label': 'Always succeeds', 'code': 'if true; then echo yes; fi'},
                           {'label': 'Infinite loop header',
                            'code': 'while true; do break; done'}]},
             {'id': '03-01-03',
              'title': 'false is a failing command',
              'points': ['The false command exists only to return failure.',
                         'It is useful for examples and disabled branches.',
                         'It behaves like any other failing command in if.'],
              'examples': [{'label': 'Always fails',
                            'code': 'if false; then echo yes; else echo no; fi'},
                           {'label': 'Fallback', 'code': 'false || echo fallback'}]},
             {'id': '03-01-04',
              'title': 'The dollar question variable',
              'points': ['$? stores the most recent command status.',
                         'Read it immediately before another command changes it.',
                         'Prefer direct if commands when possible.'],
              'examples': [{'label': 'Capture status', 'code': 'mkdir demo\nstatus=$?'},
                           {'label': 'Immediate print', 'code': 'test -d demo\necho $?'}]},
             {'id': '03-01-05',
              'title': 'Basic if then fi',
              'points': ['An if statement runs a command as its condition.',
                         'The then block runs only when the status is 0.',
                         'The fi keyword closes the conditional.'],
              'examples': [{'label': 'Directory check',
                            'code': 'if test -d /tmp; then echo exists; fi'},
                           {'label': 'Command check',
                            'code': 'if date >/dev/null; then echo ok; fi'}]},
             {'id': '03-01-06',
              'title': 'Else branch',
              'points': ['else handles the failed condition path.',
                         'It runs when the if command returns nonzero.',
                         'Use it for the single opposite outcome.'],
              'examples': [{'label': 'Path missing',
                            'code': 'if [[ -e app.log ]]; then echo found; else echo missing; fi'},
                           {'label': 'Command failed',
                            'code': 'if ping -c1 host; then echo up; else echo down; fi'}]},
             {'id': '03-01-07',
              'title': 'Elif chain',
              'points': ['elif tests another condition after a failure.',
                         'Branches are checked from top to bottom.',
                         'Only the first successful branch runs.'],
              'examples': [{'label': 'Mode branch',
                            'code': 'if [[ $mode == dev ]]; then echo d; elif [[ $mode == prod ]]; '
                                    'then echo p; fi'},
                           {'label': 'Number branch',
                            'code': 'if (( n < 0 )); then echo neg; elif (( n == 0 )); then echo '
                                    'zero; fi'}]}]},
 {'section': 2,
  'title': 'Test Commands And Strings',
  'topics': [{'id': '03-02-01',
              'title': 'The test command',
              'points': ['test evaluates file, string, and numeric expressions.',
                         'It returns 0 for true and nonzero for false.',
                         'It is a command, so if can run it directly.'],
              'examples': [{'label': 'String test',
                            'code': 'if test -n "$name"; then echo set; fi'},
                           {'label': 'File test', 'code': 'test -f config.env\necho $?'}]},
             {'id': '03-02-02',
              'title': 'Single bracket test',
              'points': ['The [ command is another spelling of test.',
                         'It requires spaces after [ and before ].',
                         'Quote variables to avoid word splitting.'],
              'examples': [{'label': 'Bracket form',
                            'code': 'if [ -f config.env ]; then echo ok; fi'},
                           {'label': 'Required spaces', 'code': '[ "$x" = yes ] && echo yes'}]},
             {'id': '03-02-03',
              'title': 'Double bracket test',
              'points': ['[[ is a Bash conditional compound command.',
                         'It avoids word splitting and pathname expansion.',
                         'It supports pattern and regex matching.'],
              'examples': [{'label': 'Safer string test',
                            'code': 'if [[ $name == root ]]; then echo admin; fi'},
                           {'label': 'Empty safe', 'code': '[[ $value == "" ]] && echo empty'}]},
             {'id': '03-02-04',
              'title': 'Empty string with -z',
              'points': ['The -z operator tests for zero string length.',
                         'It is true when a value is empty.',
                         'Use it for required argument checks.'],
              'examples': [{'label': 'Missing value',
                            'code': 'if [[ -z $user ]]; then echo missing; fi'},
                           {'label': 'Argument check', 'code': '[[ -z $1 ]] && echo need-arg'}]},
             {'id': '03-02-05',
              'title': 'Nonempty string with -n',
              'points': ['The -n operator tests for nonzero string length.',
                         'It is true when a value contains at least one character.',
                         'It is clearer than comparing to an empty string.'],
              'examples': [{'label': 'Value present',
                            'code': 'if [[ -n $token ]]; then echo set; fi'},
                           {'label': 'Prompt guard', 'code': '[[ -n $answer ]] || echo blank'}]},
             {'id': '03-02-06',
              'title': 'String equality',
              'points': ['Use == inside [[ for string equality.',
                         'Use = inside [ for portable test equality.',
                         'Quote the right side when it must be literal text.'],
              'examples': [{'label': 'Double bracket', 'code': '[[ $env == prod ]] && echo live'},
                           {'label': 'Single bracket', 'code': '[ "$env" = prod ] && echo live'}]},
             {'id': '03-02-07',
              'title': 'String inequality',
              'points': ['Use != to test that strings differ.',
                         'In [[, the right side can act as a pattern when unquoted.',
                         'Use quotes when a literal comparison matters.'],
              'examples': [{'label': 'Not equal',
                            'code': 'if [[ $env != prod ]]; then echo safe; fi'},
                           {'label': 'Literal compare',
                            'code': '[[ $name != "*.tmp" ]] && echo literal'}]}]},
 {'section': 3,
  'title': 'Patterns Regex And Integers',
  'topics': [{'id': '03-03-01',
              'title': 'Pattern matching with double brackets',
              'points': ['Inside [[, == can match glob patterns.',
                         'Leave the pattern unquoted to enable pattern matching.',
                         'Quote the pattern when matching literal characters.'],
              'examples': [{'label': 'Suffix pattern', 'code': '[[ $file == *.txt ]] && echo text'},
                           {'label': 'Prefix pattern',
                            'code': '[[ $name == app-* ]] && echo app'}]},
             {'id': '03-03-02',
              'title': 'Quoted patterns become literals',
              'points': ['A quoted right side of == is compared literally.',
                         'This prevents glob characters from acting as patterns.',
                         'Use this when user input may contain wildcard characters.'],
              'examples': [{'label': 'Literal star',
                            'code': '[[ $value == "*.txt" ]] && echo literal'},
                           {'label': 'Pattern star',
                            'code': '[[ $value == *.txt ]] && echo match'}]},
             {'id': '03-03-03',
              'title': 'Regex match operator',
              'points': ['The =~ operator matches a string against a regular expression.',
                         'The regex should usually be unquoted in [[.',
                         'Use anchors to require the whole value to match.'],
              'examples': [{'label': 'Digits only', 'code': '[[ $id =~ ^[0-9]+$ ]] && echo digits'},
                           {'label': 'Name shape',
                            'code': '[[ $name =~ ^[a-z_][a-z0-9_]*$ ]] && echo ok'}]},
             {'id': '03-03-04',
              'title': 'Integer equality operators',
              'points': ['Use -eq for integer equality in test expressions.',
                         'Use -ne for integer inequality.',
                         'These operators expect integer operands.'],
              'examples': [{'label': 'Equal', 'code': 'if [[ $count -eq 0 ]]; then echo empty; fi'},
                           {'label': 'Not equal',
                            'code': '[[ $retries -ne 3 ]] && echo keep-going'}]},
             {'id': '03-03-05',
              'title': 'Integer less than operators',
              'points': ['Use -lt to test less than.',
                         'Use -le to test less than or equal.',
                         'Prefer arithmetic syntax for complex arithmetic expressions.'],
              'examples': [{'label': 'Less than', 'code': '[[ $age -lt 18 ]] && echo minor'},
                           {'label': 'At most', 'code': '[[ $tries -le 5 ]] && echo allowed'}]},
             {'id': '03-03-06',
              'title': 'Integer greater than operators',
              'points': ['Use -gt to test greater than.',
                         'Use -ge to test greater than or equal.',
                         'Validate input before numeric comparisons.'],
              'examples': [{'label': 'Greater than', 'code': '[[ $size -gt 0 ]] && echo data'},
                           {'label': 'At least', 'code': '[[ $uid -ge 1000 ]] && echo user'}]},
             {'id': '03-03-07',
              'title': 'Arithmetic conditions',
              'points': ['The (( )) form evaluates arithmetic expressions.',
                         'A nonzero arithmetic result is true.',
                         'It is concise for counters and loop logic.'],
              'examples': [{'label': 'Counter positive',
                            'code': 'if (( count > 0 )); then echo yes; fi'},
                           {'label': 'Even check', 'code': '(( n % 2 == 0 )) && echo even'}]}]},
 {'section': 4,
  'title': 'File Tests',
  'topics': [{'id': '03-04-01',
              'title': 'Path exists with -e',
              'points': ['The -e test checks whether a path exists.',
                         'It does not care what type of path it is.',
                         'Use it before choosing a more specific file test.'],
              'examples': [{'label': 'Any path', 'code': '[[ -e config.env ]] && echo exists'},
                           {'label': 'Missing path', 'code': '[[ ! -e cache ]] && echo absent'}]},
             {'id': '03-04-02',
              'title': 'Regular file with -f',
              'points': ['The -f test checks for a regular file.',
                         'It is false for directories and most special files.',
                         'Use it before reading expected file content.'],
              'examples': [{'label': 'Config file',
                            'code': 'if [[ -f config.env ]]; then source config.env; fi'},
                           {'label': 'Skip nonfile', 'code': '[[ -f $path ]] || echo not-file'}]},
             {'id': '03-04-03',
              'title': 'Directory with -d',
              'points': ['The -d test checks for a directory.',
                         'It is useful before listing or writing inside a path.',
                         'It distinguishes directories from regular files.'],
              'examples': [{'label': 'Directory exists', 'code': '[[ -d logs ]] && echo has-logs'},
                           {'label': 'Create if missing', 'code': '[[ -d tmp ]] || mkdir tmp'}]},
             {'id': '03-04-04',
              'title': 'Symbolic link with -L',
              'points': ['The -L test checks whether a path is a symbolic link.',
                         'It is useful before replacing or resolving links.',
                         'It tests the link itself, not only the target.'],
              'examples': [{'label': 'Link check', 'code': '[[ -L current ]] && echo symlink'},
                           {'label': 'Remove link', 'code': 'if [[ -L old ]]; then rm old; fi'}]},
             {'id': '03-04-05',
              'title': 'Readable path with -r',
              'points': ['The -r test checks read permission for the current user.',
                         'It helps produce clearer errors before opening files.',
                         'Permission can still change after the test.'],
              'examples': [{'label': 'Readable file',
                            'code': '[[ -r config.env ]] && echo can-read'},
                           {'label': 'Guard read',
                            'code': 'if [[ ! -r $file ]]; then echo unreadable; fi'}]},
             {'id': '03-04-06',
              'title': 'Writable path with -w',
              'points': ['The -w test checks write permission for the current user.',
                         'It is useful before writing files or directories.',
                         'A writable directory allows creating entries inside it.'],
              'examples': [{'label': 'Writable file',
                            'code': '[[ -w report.txt ]] && echo can-write'},
                           {'label': 'Writable directory',
                            'code': '[[ -w logs ]] || echo no-write'}]},
             {'id': '03-04-07',
              'title': 'Executable path with -x',
              'points': ['The -x test checks execute permission.',
                         'For files, it means the file can be executed.',
                         'For directories, it means the directory can be searched.'],
              'examples': [{'label': 'Script executable', 'code': '[[ -x ./deploy ]] && ./deploy'},
                           {'label': 'Directory access',
                            'code': '[[ -x /tmp ]] && echo enterable'}]}]},
 {'section': 5,
  'title': 'Combining Conditions',
  'topics': [{'id': '03-05-01',
              'title': 'Nonempty file with -s',
              'points': ['The -s test checks that a file exists and has size greater than zero.',
                         'It is useful before processing generated output.',
                         'It avoids treating empty files as useful data.'],
              'examples': [{'label': 'Has content', 'code': '[[ -s results.txt ]] && echo ready'},
                           {'label': 'Empty report', 'code': '[[ -s report.txt ]] || echo empty'}]},
             {'id': '03-05-02',
              'title': 'And with double ampersand',
              'points': ['The && operator runs the right command only after success.',
                         'Inside [[, && combines true conditions.',
                         'Use it for requirements that must all pass.'],
              'examples': [{'label': 'Two tests',
                            'code': '[[ -f $file && -r $file ]] && echo usable'},
                           {'label': 'Command chain', 'code': 'mkdir out && echo made'}]},
             {'id': '03-05-03',
              'title': 'Or with double pipe',
              'points': ['The || operator runs the right command only after failure.',
                         'Inside [[, || accepts either condition.',
                         'Use it for alternatives or fallbacks.'],
              'examples': [{'label': 'Either suffix',
                            'code': '[[ $f == *.jpg || $f == *.png ]] && echo image'},
                           {'label': 'Fallback', 'code': 'cd app || exit 1'}]},
             {'id': '03-05-04',
              'title': 'Negation with exclamation',
              'points': ['The ! operator reverses success and failure.',
                         'It can negate commands or conditions.',
                         'Use it sparingly so branches remain readable.'],
              'examples': [{'label': 'Not a directory',
                            'code': 'if [[ ! -d logs ]]; then mkdir logs; fi'},
                           {'label': 'Command not found',
                            'code': 'if ! command -v jq; then echo install-jq; fi'}]},
             {'id': '03-05-05',
              'title': 'Grouping inside double brackets',
              'points': ['Parentheses group conditions inside [[.',
                         'Grouping makes precedence explicit.',
                         'Spaces are required around grouped expressions.'],
              'examples': [{'label': 'Group alternatives',
                            'code': '[[ -f $p && ( $p == *.sh || $p == *.bash ) ]] && echo shell'},
                           {'label': 'Group modes',
                            'code': '[[ $env == prod && ( $role == web || $role == api ) ]] && '
                                    'echo deploy'}]},
             {'id': '03-05-06',
              'title': 'Short circuit mkdir fallback',
              'points': ['mkdir returns failure when it cannot create a directory.',
                         'A || branch can stop the script after mkdir fails.',
                         'Use -p when parent creation and existing directories are acceptable.'],
              'examples': [{'label': 'Stop on failure', 'code': 'mkdir -p logs || exit 1'},
                           {'label': 'Message then stop',
                            'code': 'mkdir cache || { echo failed; exit 1; }'}]},
             {'id': '03-05-07',
              'title': 'Spacing mistakes in tests',
              'points': ['The [ command requires separate words for each token.',
                         'Missing spaces change the command name or arguments.',
                         'Double brackets also need spaces around the outer tokens.'],
              'examples': [{'label': 'Correct bracket', 'code': '[ -n "$name" ] && echo set'},
                           {'label': 'Correct double bracket',
                            'code': '[[ -n $name ]] && echo set'}]}]},
 {'section': 6,
  'title': 'Case Statements',
  'topics': [{'id': '03-06-01',
              'title': 'Case esac shape',
              'points': ['case compares one word against ordered patterns.',
                         'Each matching arm runs its commands.',
                         'The esac keyword closes the statement.'],
              'examples': [{'label': 'Basic case',
                            'code': 'case $cmd in start) echo go ;; stop) echo halt ;; esac'},
                           {'label': 'With variable',
                            'code': 'case $env in prod) echo live ;; *) echo other ;; esac'}]},
             {'id': '03-06-02',
              'title': 'Exact case patterns',
              'points': ['A plain word pattern matches that exact value.',
                         'Patterns are checked in order.',
                         'Use exact patterns for command names and modes.'],
              'examples': [{'label': 'Mode', 'code': 'case $mode in debug) echo debug ;; esac'},
                           {'label': 'Answer',
                            'code': 'case $answer in yes) echo ok ;; no) echo skip ;; esac'}]},
             {'id': '03-06-03',
              'title': 'Case alternatives with pipe',
              'points': ['The | character separates patterns in one case arm.',
                         'The same commands run for any listed alternative.',
                         'Use it to handle aliases cleanly.'],
              'examples': [{'label': 'Yes answers',
                            'code': 'case $ans in y|yes) echo yes ;; n|no) echo no ;; esac'},
                           {'label': 'Start aliases',
                            'code': 'case $cmd in run|start) echo starting ;; esac'}]},
             {'id': '03-06-04',
              'title': 'Case glob patterns',
              'points': ['case patterns use shell glob syntax.',
                         'A star can match any string segment.',
                         'Use globs for suffixes, prefixes, and ranges.'],
              'examples': [{'label': 'Suffix', 'code': 'case $file in *.sh) echo shell ;; esac'},
                           {'label': 'Range', 'code': 'case $key in [0-9]) echo digit ;; esac'}]},
             {'id': '03-06-05',
              'title': 'Default case arm',
              'points': ['The * pattern is commonly used as a default.',
                         'Place it last so specific patterns are checked first.',
                         'Use it for errors or fallback behavior.'],
              'examples': [{'label': 'Unknown command',
                            'code': 'case $cmd in start) echo go ;; *) echo unknown ;; esac'},
                           {'label': 'Default value',
                            'code': 'case $color in red) echo stop ;; *) echo pass ;; esac'}]},
             {'id': '03-06-06',
              'title': 'Case arm terminator',
              'points': ['The ;; token ends a case arm.',
                         'Bash does not fall through by default.',
                         'For bootcamp scripts, prefer explicit separate arms.'],
              'examples': [{'label': 'Two arms',
                            'code': 'case $n in 1) echo one ;; 2) echo two ;; esac'},
                           {'label': 'Default stop',
                            'code': 'case $x in a) echo A ;; *) echo other ;; esac'}]},
             {'id': '03-06-07',
              'title': 'Menus with case',
              'points': ['case pairs naturally with menu choices.',
                         'Each arm can call one action.',
                         'The default arm handles invalid input.'],
              'examples': [{'label': 'Choice',
                            'code': 'case $choice in 1) echo add ;; 2) echo remove ;; *) echo bad '
                                    ';; esac'},
                           {'label': 'Letter menu',
                            'code': 'case $op in q) exit 0 ;; h) echo help ;; esac'}]}]},
 {'section': 7,
  'title': 'For Loops',
  'topics': [{'id': '03-07-01',
              'title': 'For in word list',
              'points': ['A for loop assigns one word at a time to a variable.',
                         'The do block runs once for each word.',
                         'The done keyword closes the loop.'],
              'examples': [{'label': 'Names', 'code': 'for name in ann bob; do echo $name; done'},
                           {'label': 'Modes',
                            'code': 'for mode in dev test prod; do echo $mode; done'}]},
             {'id': '03-07-02',
              'title': 'For loop over quoted values',
              'points': ['Quoted items stay single loop values.',
                         'Unquoted expansions can split into multiple words.',
                         'Arrays are the cleanest way to keep values intact.'],
              'examples': [{'label': 'Quoted words',
                            'code': 'for item in "two words" three; do echo "$item"; done'},
                           {'label': 'Array values',
                            'code': 'items=("two words" three)\n'
                                    'for item in "${items[@]}"; do echo "$item"; done'}]},
             {'id': '03-07-03',
              'title': 'For loop over arguments',
              'points': ['A for loop without in uses the script arguments.',
                         'Inside functions, it uses the function arguments.',
                         'Use this when every argument gets the same handling.'],
              'examples': [{'label': 'Implicit args', 'code': 'for arg; do echo "$arg"; done'},
                           {'label': 'Explicit args',
                            'code': 'for arg in "$@"; do echo "$arg"; done'}]},
             {'id': '03-07-04',
              'title': 'For loop over globs',
              'points': ['Globs expand to matching pathnames before the loop starts.',
                         'Quote the loop variable inside the body.',
                         'Use this for simple file batches.'],
              'examples': [{'label': 'Shell scripts', 'code': 'for f in *.sh; do echo "$f"; done'},
                           {'label': 'Logs',
                            'code': 'for log in logs/*.log; do gzip "$log"; done'}]},
             {'id': '03-07-05',
              'title': 'Empty glob care',
              'points': ['An unmatched glob remains literal by default.',
                         'That can make a loop process a fake filename.',
                         'Check existence inside the loop or enable nullglob deliberately.'],
              'examples': [{'label': 'Guard glob',
                            'code': 'for f in *.csv; do [[ -e $f ]] || continue; echo "$f"; done'},
                           {'label': 'Use nullglob',
                            'code': 'shopt -s nullglob\nfor f in *.csv; do echo "$f"; done'}]},
             {'id': '03-07-06',
              'title': 'C style for loop',
              'points': ['The for (( init; test; update )) form uses arithmetic.',
                         'It is useful for numeric counters.',
                         'The loop continues while the test expression is nonzero.'],
              'examples': [{'label': 'Count up', 'code': 'for ((i=0; i<3; i++)); do echo $i; done'},
                           {'label': 'Count down',
                            'code': 'for ((i=3; i>0; i--)); do echo $i; done'}]},
             {'id': '03-07-07',
              'title': 'Arithmetic step in for',
              'points': ['The update expression can change by more than one.',
                         'Use += and -= for clear step sizes.',
                         'Keep loop bounds easy to audit.'],
              'examples': [{'label': 'Step by two',
                            'code': 'for ((i=0; i<10; i+=2)); do echo $i; done'},
                           {'label': 'Halve',
                            'code': 'for ((n=8; n>0; n/=2)); do echo $n; done'}]}]},
 {'section': 8,
  'title': 'While Until And Read',
  'topics': [{'id': '03-08-01',
              'title': 'While loop',
              'points': ['while repeats while its condition command succeeds.',
                         'The condition is checked before each iteration.',
                         'Use it when the number of iterations is not fixed.'],
              'examples': [{'label': 'Counter',
                            'code': 'i=0\nwhile (( i < 3 )); do echo $((i++)); done'},
                           {'label': 'Readiness',
                            'code': 'while [[ ! -f done.flag ]]; do sleep 1; done'}]},
             {'id': '03-08-02',
              'title': 'Until loop',
              'points': ['until repeats while its condition command fails.',
                         'It stops when the condition succeeds.',
                         'Use it when waiting for success reads naturally.'],
              'examples': [{'label': 'Wait for file',
                            'code': 'until [[ -f ready ]]; do sleep 1; done'},
                           {'label': 'Retry command',
                            'code': 'until curl -fsS http://localhost; do sleep 2; done'}]},
             {'id': '03-08-03',
              'title': 'Break exits a loop',
              'points': ['break stops the nearest enclosing loop.',
                         'It is useful when a success condition appears early.',
                         'Avoid hidden break paths in long loop bodies.'],
              'examples': [{'label': 'Find first',
                            'code': 'for f in *.log; do [[ -s $f ]] && { echo $f; break; }; done'},
                           {'label': 'Stop menu',
                            'code': 'while true; do read -r x; [[ $x == q ]] && break; done'}]},
             {'id': '03-08-04',
              'title': 'Continue skips to the next iteration',
              'points': ['continue skips the rest of the current loop body.',
                         'It is useful for filtering invalid items.',
                         'Use early continue statements to reduce nesting.'],
              'examples': [{'label': 'Skip dirs',
                            'code': 'for p in *; do [[ -d $p ]] && continue; echo $p; done'},
                           {'label': 'Skip blanks',
                            'code': 'while read -r line; do [[ -z $line ]] && continue; echo '
                                    '$line; done'}]},
             {'id': '03-08-05',
              'title': 'Infinite loops need exits',
              'points': ['Infinite loops are intentional only with a clear exit path.',
                         'Use break, return, or exit for controlled termination.',
                         'Add sleeps when polling to avoid busy waiting.'],
              'examples': [{'label': 'Menu loop',
                            'code': 'while true; do read -r c; [[ $c == q ]] && break; done'},
                           {'label': 'Polling loop',
                            'code': 'while true; do [[ -f ready ]] && break; sleep 1; done'}]},
             {'id': '03-08-06',
              'title': 'Reading lines with while read',
              'points': ['read gets one line of input at a time.',
                         'A while read loop is standard for line processing.',
                         'Redirect the file into the loop for predictable scope.'],
              'examples': [{'label': 'Read file',
                            'code': 'while read -r line; do echo "$line"; done < names.txt'},
                           {'label': 'Number lines',
                            'code': 'n=0\n'
                                    'while read -r line; do echo $((++n)): $line; done < file'}]},
             {'id': '03-08-07',
              'title': 'IFS read r',
              'points': ['IFS= preserves leading and trailing whitespace for read.',
                         'The -r option prevents backslash escapes.',
                         'Together they are the safe default for raw lines.'],
              'examples': [{'label': 'Safe read',
                            'code': 'while IFS= read -r line; do printf \'%s\\n\' "$line"; done < '
                                    'file'},
                           {'label': 'Prompt read', 'code': 'IFS= read -r answer'}]}]},
 {'section': 9,
  'title': 'Pipelines Select And Arrays',
  'topics': [{'id': '03-09-01',
              'title': 'Pipelines in if',
              'points': ['An if condition can be a pipeline.',
                         'The pipeline status normally comes from the last command.',
                         'pipefail changes how pipeline failures are reported.'],
              'examples': [{'label': 'Search output',
                            'code': "if ps aux | grep -q '[s]shd'; then echo running; fi"},
                           {'label': 'Count match',
                            'code': "if printf '%s\\n' a b | grep -q b; then echo found; fi"}]},
             {'id': '03-09-02',
              'title': 'Pipeline while read scope',
              'points': ['A pipeline may run the while loop in a subshell.',
                         'Variable changes can disappear after the loop.',
                         'Use redirection when the final variable value matters.'],
              'examples': [{'label': 'Pipeline count',
                            'code': "printf '%s\\n' a b | while read -r x; do echo $x; done"},
                           {'label': 'Avoid counting outside',
                            'code': 'count=0\nprintf x | while read -r _; do ((count++)); done'}]},
             {'id': '03-09-03',
              'title': 'Redirected while read',
              'points': ['Redirecting input into a loop keeps the loop in the current shell.',
                         'This is preferred when updating variables.',
                         'It also makes the input source easy to spot.'],
              'examples': [{'label': 'Count lines',
                            'code': 'count=0\nwhile read -r _; do ((count++)); done < file'},
                           {'label': 'Collect names',
                            'code': 'while read -r name; do echo "hi $name"; done < names.txt'}]},
             {'id': '03-09-04',
              'title': 'Mapfile intro',
              'points': ['mapfile reads lines into an array.',
                         'It is useful when later code needs random access.',
                         'Use -t to remove trailing newlines.'],
              'examples': [{'label': 'Read array',
                            'code': 'mapfile -t lines < names.txt\necho "${#lines[@]}"'},
                           {'label': 'First line',
                            'code': 'mapfile -t rows < data.txt\necho "${rows[0]}"'}]},
             {'id': '03-09-05',
              'title': 'Readarray alias',
              'points': ['readarray is another name for mapfile.',
                         'Both are Bash builtins in Bash 4 and later.',
                         'Use the spelling your team finds clearer.'],
              'examples': [{'label': 'Readarray',
                            'code': 'readarray -t files < list.txt\n'
                                    'printf \'%s\\n\' "${files[@]}"'},
                           {'label': 'Count rows',
                            'code': 'readarray -t rows < data.txt\necho "${#rows[@]}"'}]},
             {'id': '03-09-06',
              'title': 'Select menu',
              'points': ['select builds a numbered menu from words.',
                         'It stores the selected item in the loop variable.',
                         'Use break when the user makes a valid choice.'],
              'examples': [{'label': 'Simple select',
                            'code': 'select env in dev prod quit; do echo "$env"; break; done'},
                           {'label': 'Case with select',
                            'code': 'select op in add quit; do case $op in quit) break ;; esac; '
                                    'done'}]},
             {'id': '03-09-07',
              'title': 'PS3 select prompt',
              'points': ['PS3 controls the prompt displayed by select.',
                         'Set it before the select loop.',
                         'Keep prompts short and action oriented.'],
              'examples': [{'label': 'Custom prompt',
                            'code': "PS3='Choose: '\n"
                                    'select item in one two; do echo "$item"; break; done'},
                           {'label': 'Menu prompt',
                            'code': "PS3='Action: '\nselect op in build test; do break; done"}]}]},
 {'section': 10,
  'title': 'Validation Patterns',
  'topics': [{'id': '03-10-01',
              'title': 'Validate integers with regex',
              'points': ['Use =~ to confirm input is an integer before math.',
                         'Anchors prevent partial matches.',
                         'A sign can be allowed explicitly when needed.'],
              'examples': [{'label': 'Unsigned integer',
                            'code': '[[ $n =~ ^[0-9]+$ ]] || echo not-int'},
                           {'label': 'Signed integer',
                            'code': '[[ $n =~ ^-?[0-9]+$ ]] && echo int'}]},
             {'id': '03-10-02',
              'title': 'Validate nonnegative counts',
              'points': ['Counts often require zero or positive values.',
                         'Regex validation avoids arithmetic errors from text.',
                         'Follow validation with numeric range checks if needed.'],
              'examples': [{'label': 'Count value',
                            'code': 'if [[ $count =~ ^[0-9]+$ ]]; then echo ok; fi'},
                           {'label': 'Positive value',
                            'code': '[[ $n =~ ^[0-9]+$ && $n -gt 0 ]] && echo positive'}]},
             {'id': '03-10-03',
              'title': 'Validate path existence',
              'points': ['Check that a path exists before acting on it.',
                         'Use -e when any path type is acceptable.',
                         'Report the path in error messages.'],
              'examples': [{'label': 'Require path',
                            'code': '[[ -e $path ]] || { echo "missing: $path"; exit 1; }'},
                           {'label': 'Optional path',
                            'code': 'if [[ -e $path ]]; then echo found; fi'}]},
             {'id': '03-10-04',
              'title': 'Validate readable files',
              'points': ['Readable file checks combine -f and -r.',
                         'This rejects directories and unreadable files.',
                         'Use it before parsing configuration.'],
              'examples': [{'label': 'Config guard', 'code': '[[ -f $cfg && -r $cfg ]] || exit 1'},
                           {'label': 'Read branch',
                            'code': 'if [[ -r $file ]]; then wc -l < "$file"; fi'}]},
             {'id': '03-10-05',
              'title': 'Validate writable directories',
              'points': ['Writable directory checks combine -d and -w.',
                         'Use them before creating output files.',
                         'This gives faster feedback than a failed write later.'],
              'examples': [{'label': 'Output directory',
                            'code': '[[ -d $out && -w $out ]] || exit 1'},
                           {'label': 'Create output', 'code': '[[ -d out ]] || mkdir out'}]},
             {'id': '03-10-06',
              'title': 'Validate commands with command v',
              'points': ['command -v checks whether a command can be found.',
                         'It works for builtins, functions, and executables.',
                         'Use it before relying on optional tools.'],
              'examples': [{'label': 'Need jq',
                            'code': 'if ! command -v jq >/dev/null; then echo need-jq; fi'},
                           {'label': 'Need git', 'code': 'command -v git >/dev/null || exit 1'}]},
             {'id': '03-10-07',
              'title': 'Error branches',
              'points': ['Validation failures should take a clear branch.',
                         'Use exit or return after fatal errors.',
                         'Keep the success path easy to read.'],
              'examples': [{'label': 'Fatal branch',
                            'code': '[[ -n $name ]] || { echo name-required; exit 1; }'},
                           {'label': 'Nonfatal branch',
                            'code': 'if [[ -z $tag ]]; then tag=latest; fi'}]}]},
 {'section': 11,
  'title': 'Nested Logic Retry And Timeouts',
  'topics': [{'id': '03-11-01',
              'title': 'Nested if',
              'points': ['Nested if statements express dependent decisions.',
                         'Each inner test should rely on the outer branch being true.',
                         'Too much nesting can hide the main path.'],
              'examples': [{'label': 'Nested check',
                            'code': 'if [[ -d repo ]]; then if [[ -f repo/config ]]; then echo ok; '
                                    'fi; fi'},
                           {'label': 'Nested command',
                            'code': 'if cd repo; then if git status; then echo clean; fi; fi'}]},
             {'id': '03-11-02',
              'title': 'Guard clauses reduce nesting',
              'points': ['A guard clause exits early when a requirement fails.',
                         'It keeps the main branch less indented.',
                         'Use it for fatal validation checks.'],
              'examples': [{'label': 'Require arg', 'code': '[[ -n $1 ]] || exit 2\necho "arg=$1"'},
                           {'label': 'Require dir', 'code': '[[ -d src ]] || exit 1\necho build'}]},
             {'id': '03-11-03',
              'title': 'Retry loop',
              'points': ['A retry loop repeats a command after failure.',
                         'Limit retries so failures do not run forever.',
                         'Break as soon as the command succeeds.'],
              'examples': [{'label': 'Three tries',
                            'code': 'for i in 1 2 3; do curl -fsS URL && break; done'},
                           {'label': 'Retry flag',
                            'code': 'ok=0\nfor i in 1 2 3; do command && { ok=1; break; }; done'}]},
             {'id': '03-11-04',
              'title': 'Sleep between retries',
              'points': ['sleep adds delay between attempts.',
                         'It protects services from tight retry loops.',
                         'Keep retry delays visible in the loop body.'],
              'examples': [{'label': 'Sleep retry',
                            'code': 'for i in 1 2 3; do curl -fsS URL && break; sleep 2; done'},
                           {'label': 'Until sleep',
                            'code': 'until nc -z host 80; do sleep 1; done'}]},
             {'id': '03-11-05',
              'title': 'Timeout command',
              'points': ['timeout limits how long a command may run.',
                         'It returns failure when the time limit is reached.',
                         'Use it around network or interactive commands.'],
              'examples': [{'label': 'Limit curl',
                            'code': 'if timeout 5 curl -fsS URL; then echo ok; fi'},
                           {'label': 'Limit read',
                            'code': "if timeout 10 bash -c 'read -r x'; then echo got; fi"}]},
             {'id': '03-11-06',
              'title': 'Failure limit',
              'points': ['Track attempts when retrying manually.',
                         'Stop after a known maximum failure count.',
                         'Return or exit after exhausting retries.'],
              'examples': [{'label': 'Attempt counter',
                            'code': 'tries=0\nuntil cmd; do ((++tries == 3)) && exit 1; done'},
                           {'label': 'Loop bound',
                            'code': 'for ((i=1; i<=3; i++)); do cmd && break; done'}]},
             {'id': '03-11-07',
              'title': 'Break on success',
              'points': ['Successful work often ends a search loop.',
                         'Use break immediately after the success action.',
                         'This avoids processing unnecessary later items.'],
              'examples': [{'label': 'First match',
                            'code': 'for f in *.txt; do grep -q needle "$f" && { echo "$f"; break; '
                                    '}; done'},
                           {'label': 'First port',
                            'code': 'for p in 8000 8001; do nc -z localhost $p && { echo $p; '
                                    'break; }; done'}]}]},
 {'section': 12,
  'title': 'Practice And Checkpoints',
  'topics': [{'id': '03-12-01',
              'title': 'If command practice',
              'points': ['Use if directly with the command being tested.',
                         'Avoid checking $? when an if command is clearer.',
                         'Redirect noisy command output when only status matters.'],
              'examples': [{'label': 'Grep status',
                            'code': 'if grep -q root /etc/passwd; then echo found; fi'},
                           {'label': 'Git status',
                            'code': 'if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then '
                                    'echo repo; fi'}]},
             {'id': '03-12-02',
              'title': 'Case dispatch practice',
              'points': ['Use case to dispatch small command names.',
                         'Keep each arm focused on one action.',
                         'Route unknown commands to a usage error.'],
              'examples': [{'label': 'Dispatch',
                            'code': 'case $1 in build) echo build ;; test) echo test ;; *) echo '
                                    'usage ;; esac'},
                           {'label': 'Aliases',
                            'code': 'case $1 in rm|delete) echo remove ;; *) echo unknown ;; '
                                    'esac'}]},
             {'id': '03-12-03',
              'title': 'File loop practice',
              'points': ['Combine globs with file tests for safe batches.',
                         'Skip nonmatching or invalid paths early.',
                         'Quote each pathname inside the loop body.'],
              'examples': [{'label': 'Readable logs',
                            'code': 'for f in logs/*.log; do [[ -r $f ]] || continue; echo "$f"; '
                                    'done'},
                           {'label': 'Executable scripts',
                            'code': 'for f in bin/*; do [[ -x $f ]] && echo "$f"; done'}]},
             {'id': '03-12-04',
              'title': 'Prompt until valid',
              'points': ['A while loop can repeat until input passes validation.',
                         'Validate immediately after each read.',
                         'Use break when a valid answer is accepted.'],
              'examples': [{'label': 'Ask number',
                            'code': 'while true; do read -r n; [[ $n =~ ^[0-9]+$ ]] && break; '
                                    'done'},
                           {'label': 'Ask yes no',
                            'code': 'while read -r a; do [[ $a == y || $a == n ]] && break; '
                                    'done'}]},
             {'id': '03-12-05',
              'title': 'Select and case practice',
              'points': ['select provides the menu display.',
                         'case handles the selected action.',
                         'Invalid or empty choices should continue the menu.'],
              'examples': [{'label': 'Action menu',
                            'code': 'select op in build quit; do case $op in quit) break ;; build) '
                                    'echo build ;; esac; done'},
                           {'label': 'Environment menu',
                            'code': 'select env in dev prod; do [[ -n $env ]] && break; done'}]},
             {'id': '03-12-06',
              'title': 'Missing fi mistake',
              'points': ['Every if statement must end with fi.',
                         'Missing fi often reports a syntax error later in the file.',
                         'Indentation helps humans see the matching structure.'],
              'examples': [{'label': 'Closed if', 'code': 'if [[ -n $x ]]; then echo set; fi'},
                           {'label': 'Nested closed',
                            'code': 'if [[ -d a ]]; then if [[ -f a/b ]]; then echo ok; fi; fi'}]},
             {'id': '03-12-07',
              'title': 'Control flow checkpoint',
              'points': ['Choose if for command status and simple decisions.',
                         'Choose case for one value matched against many patterns.',
                         'Choose loops based on whether input is a list, condition, or menu.'],
              'examples': [{'label': 'Decision',
                            'code': '[[ -f config ]] && echo file || echo missing'},
                           {'label': 'Loop', 'code': 'for f in *.sh; do bash -n "$f"; done'}]}]}]
